// JavaScript Document

//cookie
(function(g){g.cookie=function(h,b,a){if(1<arguments.length&&(!/Object/.test(Object.prototype.toString.call(b))||null===b||void 0===b)){a=g.extend({},a);if(null===b||void 0===b)a.expires=-1;if("number"===typeof a.expires){var d=a.expires,c=a.expires=new Date;c.setDate(c.getDate()+d)}b=""+b;return document.cookie=[encodeURIComponent(h),"=",a.raw?b:encodeURIComponent(b),a.expires?"; expires="+a.expires.toUTCString():"",a.path?"; path="+a.path:"",a.domain?"; domain="+a.domain:"",a.secure?"; secure":
""].join("")}for(var a=b||{},d=a.raw?function(a){return a}:decodeURIComponent,c=document.cookie.split("; "),e=0,f;f=c[e]&&c[e].split("=");e++)if(d(f[0])===h)return d(f[1]||"");return null}})(jQuery);

//validate
(function(c){c.extend(c.fn,{validate:function(a){if(this.length){var b=c.data(this[0],"validator");if(b)return b;b=new c.validator(a,this[0]);c.data(this[0],"validator",b);if(b.settings.onsubmit){this.find("input, button").filter(".cancel").click(function(){b.cancelSubmit=true});b.settings.submitHandler&&this.find("input, button").filter(":submit").click(function(){b.submitButton=this});this.submit(function(d){function e(){if(b.settings.submitHandler){if(b.submitButton)var f=c("<input type='hidden'/>").attr("name",
b.submitButton.name).val(b.submitButton.value).appendTo(b.currentForm);b.settings.submitHandler.call(b,b.currentForm);b.submitButton&&f.remove();return false}return true}b.settings.debug&&d.preventDefault();if(b.cancelSubmit){b.cancelSubmit=false;return e()}if(b.form()){if(b.pendingRequest){b.formSubmitted=true;return false}return e()}else{b.focusInvalid();return false}})}return b}else a&&a.debug&&window.console&&console.warn("nothing selected, can't validate, returning nothing")},valid:function(){if(c(this[0]).is("form"))return this.validate().form();
else{var a=true,b=c(this[0].form).validate();this.each(function(){a&=b.element(this)});return a}},removeAttrs:function(a){var b={},d=this;c.each(a.split(/\s/),function(e,f){b[f]=d.attr(f);d.removeAttr(f)});return b},rules:function(a,b){var d=this[0];if(a){var e=c.data(d.form,"validator").settings,f=e.rules,g=c.validator.staticRules(d);switch(a){case "add":c.extend(g,c.validator.normalizeRule(b));f[d.name]=g;if(b.messages)e.messages[d.name]=c.extend(e.messages[d.name],b.messages);break;case "remove":if(!b){delete f[d.name];
return g}var h={};c.each(b.split(/\s/),function(j,i){h[i]=g[i];delete g[i]});return h}}d=c.validator.normalizeRules(c.extend({},c.validator.metadataRules(d),c.validator.classRules(d),c.validator.attributeRules(d),c.validator.staticRules(d)),d);if(d.required){e=d.required;delete d.required;d=c.extend({required:e},d)}return d}});c.extend(c.expr[":"],{blank:function(a){return!c.trim(""+a.value)},filled:function(a){return!!c.trim(""+a.value)},unchecked:function(a){return!a.checked}});c.validator=function(a,
b){this.settings=c.extend(true,{},c.validator.defaults,a);this.currentForm=b;this.init()};c.validator.format=function(a,b){if(arguments.length==1)return function(){var d=c.makeArray(arguments);d.unshift(a);return c.validator.format.apply(this,d)};if(arguments.length>2&&b.constructor!=Array)b=c.makeArray(arguments).slice(1);if(b.constructor!=Array)b=[b];c.each(b,function(d,e){a=a.replace(RegExp("\\{"+d+"\\}","g"),e)});return a};c.extend(c.validator,{defaults:{messages:{},groups:{},rules:{},errorClass:"error",
validClass:"valid",errorElement:"label",focusInvalid:true,errorContainer:c([]),errorLabelContainer:c([]),onsubmit:true,ignore:[],ignoreTitle:false,onfocusin:function(a){this.lastActive=a;if(this.settings.focusCleanup&&!this.blockFocusCleanup){this.settings.unhighlight&&this.settings.unhighlight.call(this,a,this.settings.errorClass,this.settings.validClass);this.addWrapper(this.errorsFor(a)).hide()}},onfocusout:function(a){if(!this.checkable(a)&&(a.name in this.submitted||!this.optional(a)))this.element(a)},
onkeyup:function(a){if(a.name in this.submitted||a==this.lastElement)this.element(a)},onclick:function(a){if(a.name in this.submitted)this.element(a);else a.parentNode.name in this.submitted&&this.element(a.parentNode)},highlight:function(a,b,d){a.type==="radio"?this.findByName(a.name).addClass(b).removeClass(d):c(a).addClass(b).removeClass(d)},unhighlight:function(a,b,d){a.type==="radio"?this.findByName(a.name).removeClass(b).addClass(d):c(a).removeClass(b).addClass(d)}},setDefaults:function(a){c.extend(c.validator.defaults,
a)},messages:{required:"This field is required.",remote:"Please fix this field.",email:"Please enter a valid email address.",url:"Please enter a valid URL.",date:"Please enter a valid date.",dateISO:"Please enter a valid date (ISO).",number:"Please enter a valid number.",digits:"Please enter only digits.",creditcard:"Please enter a valid credit card number.",equalTo:"Please enter the same value again.",accept:"Please enter a value with a valid extension.",maxlength:c.validator.format("Please enter no more than {0} characters."),
minlength:c.validator.format("Please enter at least {0} characters."),rangelength:c.validator.format("Please enter a value between {0} and {1} characters long."),range:c.validator.format("Please enter a value between {0} and {1}."),max:c.validator.format("Please enter a value less than or equal to {0}."),min:c.validator.format("Please enter a value greater than or equal to {0}.")},autoCreateRanges:false,prototype:{init:function(){function a(e){var f=c.data(this[0].form,"validator");e="on"+e.type.replace(/^validate/,
"");f.settings[e]&&f.settings[e].call(f,this[0])}this.labelContainer=c(this.settings.errorLabelContainer);this.errorContext=this.labelContainer.length&&this.labelContainer||c(this.currentForm);this.containers=c(this.settings.errorContainer).add(this.settings.errorLabelContainer);this.submitted={};this.valueCache={};this.pendingRequest=0;this.pending={};this.invalid={};this.reset();var b=this.groups={};c.each(this.settings.groups,function(e,f){c.each(f.split(/\s/),function(g,h){b[h]=e})});var d=this.settings.rules;
c.each(d,function(e,f){d[e]=c.validator.normalizeRule(f)});c(this.currentForm).validateDelegate(":text, :password, :file, select, textarea","focusin focusout keyup",a).validateDelegate(":radio, :checkbox, select, option","click",a);this.settings.invalidHandler&&c(this.currentForm).bind("invalid-form.validate",this.settings.invalidHandler)},form:function(){this.checkForm();c.extend(this.submitted,this.errorMap);this.invalid=c.extend({},this.errorMap);this.valid()||c(this.currentForm).triggerHandler("invalid-form",
[this]);this.showErrors();return this.valid()},checkForm:function(){this.prepareForm();for(var a=0,b=this.currentElements=this.elements();b[a];a++)this.check(b[a]);return this.valid()},element:function(a){this.lastElement=a=this.clean(a);this.prepareElement(a);this.currentElements=c(a);var b=this.check(a);if(b)delete this.invalid[a.name];else this.invalid[a.name]=true;if(!this.numberOfInvalids())this.toHide=this.toHide.add(this.containers);this.showErrors();return b},showErrors:function(a){if(a){c.extend(this.errorMap,
a);this.errorList=[];for(var b in a)this.errorList.push({message:a[b],element:this.findByName(b)[0]});this.successList=c.grep(this.successList,function(d){return!(d.name in a)})}this.settings.showErrors?this.settings.showErrors.call(this,this.errorMap,this.errorList):this.defaultShowErrors()},resetForm:function(){c.fn.resetForm&&c(this.currentForm).resetForm();this.submitted={};this.prepareForm();this.hideErrors();this.elements().removeClass(this.settings.errorClass)},numberOfInvalids:function(){return this.objectLength(this.invalid)},
objectLength:function(a){var b=0,d;for(d in a)b++;return b},hideErrors:function(){this.addWrapper(this.toHide).hide()},valid:function(){return this.size()==0},size:function(){return this.errorList.length},focusInvalid:function(){if(this.settings.focusInvalid)try{c(this.findLastActive()||this.errorList.length&&this.errorList[0].element||[]).filter(":visible").focus().trigger("focusin")}catch(a){}},findLastActive:function(){var a=this.lastActive;return a&&c.grep(this.errorList,function(b){return b.element.name==
a.name}).length==1&&a},elements:function(){var a=this,b={};return c(this.currentForm).find("input, select, textarea").not(":submit, :reset, :image, [disabled]").not(this.settings.ignore).filter(function(){!this.name&&a.settings.debug&&window.console&&console.error("%o has no name assigned",this);if(this.name in b||!a.objectLength(c(this).rules()))return false;return b[this.name]=true})},clean:function(a){return c(a)[0]},errors:function(){return c(this.settings.errorElement+"."+this.settings.errorClass,
this.errorContext)},reset:function(){this.successList=[];this.errorList=[];this.errorMap={};this.toShow=c([]);this.toHide=c([]);this.currentElements=c([])},prepareForm:function(){this.reset();this.toHide=this.errors().add(this.containers)},prepareElement:function(a){this.reset();this.toHide=this.errorsFor(a)},check:function(a){a=this.clean(a);if(this.checkable(a))a=this.findByName(a.name).not(this.settings.ignore)[0];var b=c(a).rules(),d=false,e;for(e in b){var f={method:e,parameters:b[e]};try{var g=
c.validator.methods[e].call(this,a.value.replace(/\r/g,""),a,f.parameters);if(g=="dependency-mismatch")d=true;else{d=false;if(g=="pending"){this.toHide=this.toHide.not(this.errorsFor(a));return}if(!g){this.formatAndAdd(a,f);return false}}}catch(h){this.settings.debug&&window.console&&console.log("exception occured when checking element "+a.id+", check the '"+f.method+"' method",h);throw h;}}if(!d){this.objectLength(b)&&this.successList.push(a);return true}},customMetaMessage:function(a,b){if(c.metadata){var d=
this.settings.meta?c(a).metadata()[this.settings.meta]:c(a).metadata();return d&&d.messages&&d.messages[b]}},customMessage:function(a,b){var d=this.settings.messages[a];return d&&(d.constructor==String?d:d[b])},findDefined:function(){for(var a=0;a<arguments.length;a++)if(arguments[a]!==undefined)return arguments[a]},defaultMessage:function(a,b){return this.findDefined(this.customMessage(a.name,b),this.customMetaMessage(a,b),!this.settings.ignoreTitle&&a.title||undefined,c.validator.messages[b],"<strong>Warning: No message defined for "+
a.name+"</strong>")},formatAndAdd:function(a,b){var d=this.defaultMessage(a,b.method),e=/\$?\{(\d+)\}/g;if(typeof d=="function")d=d.call(this,b.parameters,a);else if(e.test(d))d=jQuery.format(d.replace(e,"{$1}"),b.parameters);this.errorList.push({message:d,element:a});this.errorMap[a.name]=d;this.submitted[a.name]=d},addWrapper:function(a){if(this.settings.wrapper)a=a.add(a.parent(this.settings.wrapper));return a},defaultShowErrors:function(){for(var a=0;this.errorList[a];a++){var b=this.errorList[a];
this.settings.highlight&&this.settings.highlight.call(this,b.element,this.settings.errorClass,this.settings.validClass);this.showLabel(b.element,b.message)}if(this.errorList.length)this.toShow=this.toShow.add(this.containers);if(this.settings.success)for(a=0;this.successList[a];a++)this.showLabel(this.successList[a]);if(this.settings.unhighlight){a=0;for(b=this.validElements();b[a];a++)this.settings.unhighlight.call(this,b[a],this.settings.errorClass,this.settings.validClass)}this.toHide=this.toHide.not(this.toShow);
this.hideErrors();this.addWrapper(this.toShow).show()},validElements:function(){return this.currentElements.not(this.invalidElements())},invalidElements:function(){return c(this.errorList).map(function(){return this.element})},showLabel:function(a,b){var d=this.errorsFor(a);if(d.length){d.removeClass().addClass(this.settings.errorClass);d.attr("generated")&&d.html(b)}else{d=c("<"+this.settings.errorElement+"/>").attr({"for":this.idOrName(a),generated:true}).addClass(this.settings.errorClass).html(b||
"");if(this.settings.wrapper)d=d.hide().show().wrap("<"+this.settings.wrapper+"/>").parent();this.labelContainer.append(d).length||(this.settings.errorPlacement?this.settings.errorPlacement(d,c(a)):d.insertAfter(a))}if(!b&&this.settings.success){d.text("");typeof this.settings.success=="string"?d.addClass(this.settings.success):this.settings.success(d)}this.toShow=this.toShow.add(d)},errorsFor:function(a){var b=this.idOrName(a);return this.errors().filter(function(){return c(this).attr("for")==b})},
idOrName:function(a){return this.groups[a.name]||(this.checkable(a)?a.name:a.id||a.name)},checkable:function(a){return/radio|checkbox/i.test(a.type)},findByName:function(a){var b=this.currentForm;return c(document.getElementsByName(a)).map(function(d,e){return e.form==b&&e.name==a&&e||null})},getLength:function(a,b){switch(b.nodeName.toLowerCase()){case "select":return c("option:selected",b).length;case "input":if(this.checkable(b))return this.findByName(b.name).filter(":checked").length}return a.length},
depend:function(a,b){return this.dependTypes[typeof a]?this.dependTypes[typeof a](a,b):true},dependTypes:{"boolean":function(a){return a},string:function(a,b){return!!c(a,b.form).length},"function":function(a,b){return a(b)}},optional:function(a){return!c.validator.methods.required.call(this,c.trim(a.value),a)&&"dependency-mismatch"},startRequest:function(a){if(!this.pending[a.name]){this.pendingRequest++;this.pending[a.name]=true}},stopRequest:function(a,b){this.pendingRequest--;if(this.pendingRequest<
0)this.pendingRequest=0;delete this.pending[a.name];if(b&&this.pendingRequest==0&&this.formSubmitted&&this.form()){c(this.currentForm).submit();this.formSubmitted=false}else if(!b&&this.pendingRequest==0&&this.formSubmitted){c(this.currentForm).triggerHandler("invalid-form",[this]);this.formSubmitted=false}},previousValue:function(a){return c.data(a,"previousValue")||c.data(a,"previousValue",{old:null,valid:true,message:this.defaultMessage(a,"remote")})}},classRuleSettings:{required:{required:true},
email:{email:true},url:{url:true},date:{date:true},dateISO:{dateISO:true},dateDE:{dateDE:true},number:{number:true},numberDE:{numberDE:true},digits:{digits:true},creditcard:{creditcard:true}},addClassRules:function(a,b){a.constructor==String?this.classRuleSettings[a]=b:c.extend(this.classRuleSettings,a)},classRules:function(a){var b={};(a=c(a).attr("class"))&&c.each(a.split(" "),function(){this in c.validator.classRuleSettings&&c.extend(b,c.validator.classRuleSettings[this])});return b},attributeRules:function(a){var b=
{};a=c(a);for(var d in c.validator.methods){var e=a.attr(d);if(e)b[d]=e}b.maxlength&&/-1|2147483647|524288/.test(b.maxlength)&&delete b.maxlength;return b},metadataRules:function(a){if(!c.metadata)return{};var b=c.data(a.form,"validator").settings.meta;return b?c(a).metadata()[b]:c(a).metadata()},staticRules:function(a){var b={},d=c.data(a.form,"validator");if(d.settings.rules)b=c.validator.normalizeRule(d.settings.rules[a.name])||{};return b},normalizeRules:function(a,b){c.each(a,function(d,e){if(e===
false)delete a[d];else if(e.param||e.depends){var f=true;switch(typeof e.depends){case "string":f=!!c(e.depends,b.form).length;break;case "function":f=e.depends.call(b,b)}if(f)a[d]=e.param!==undefined?e.param:true;else delete a[d]}});c.each(a,function(d,e){a[d]=c.isFunction(e)?e(b):e});c.each(["minlength","maxlength","min","max"],function(){if(a[this])a[this]=Number(a[this])});c.each(["rangelength","range"],function(){if(a[this])a[this]=[Number(a[this][0]),Number(a[this][1])]});if(c.validator.autoCreateRanges){if(a.min&&
a.max){a.range=[a.min,a.max];delete a.min;delete a.max}if(a.minlength&&a.maxlength){a.rangelength=[a.minlength,a.maxlength];delete a.minlength;delete a.maxlength}}a.messages&&delete a.messages;return a},normalizeRule:function(a){if(typeof a=="string"){var b={};c.each(a.split(/\s/),function(){b[this]=true});a=b}return a},addMethod:function(a,b,d){c.validator.methods[a]=b;c.validator.messages[a]=d!=undefined?d:c.validator.messages[a];b.length<3&&c.validator.addClassRules(a,c.validator.normalizeRule(a))},
methods:{required:function(a,b,d){if(!this.depend(d,b))return"dependency-mismatch";switch(b.nodeName.toLowerCase()){case "select":return(a=c(b).val())&&a.length>0;case "input":if(this.checkable(b))return this.getLength(a,b)>0;default:return c.trim(a).length>0}},remote:function(a,b,d){if(this.optional(b))return"dependency-mismatch";var e=this.previousValue(b);this.settings.messages[b.name]||(this.settings.messages[b.name]={});e.originalMessage=this.settings.messages[b.name].remote;this.settings.messages[b.name].remote=
e.message;d=typeof d=="string"&&{url:d}||d;if(this.pending[b.name])return"pending";if(e.old===a)return e.valid;e.old=a;var f=this;this.startRequest(b);var g={};g[b.name]=a;c.ajax(c.extend(true,{url:d,mode:"abort",port:"validate"+b.name,dataType:"json",data:g,success:function(h){f.settings.messages[b.name].remote=e.originalMessage;var j=h===true;if(j){var i=f.formSubmitted;f.prepareElement(b);f.formSubmitted=i;f.successList.push(b);f.showErrors()}else{i={};h=h||f.defaultMessage(b,"remote");i[b.name]=
e.message=c.isFunction(h)?h(a):h;f.showErrors(i)}e.valid=j;f.stopRequest(b,j)}},d));return"pending"},minlength:function(a,b,d){return this.optional(b)||this.getLength(c.trim(a),b)>=d},maxlength:function(a,b,d){return this.optional(b)||this.getLength(c.trim(a),b)<=d},rangelength:function(a,b,d){a=this.getLength(c.trim(a),b);return this.optional(b)||a>=d[0]&&a<=d[1]},min:function(a,b,d){return this.optional(b)||a>=d},max:function(a,b,d){return this.optional(b)||a<=d},range:function(a,b,d){return this.optional(b)||
a>=d[0]&&a<=d[1]},email:function(a,b){return this.optional(b)||/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/i.test(a)},
url:function(a,b){return this.optional(b)||/^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i.test(a)},
date:function(a,b){return this.optional(b)||!/Invalid|NaN/.test(new Date(a))},dateISO:function(a,b){return this.optional(b)||/^\d{4}[\/-]\d{1,2}[\/-]\d{1,2}$/.test(a)},number:function(a,b){return this.optional(b)||/^-?(?:\d+|\d{1,3}(?:,\d{3})+)(?:\.\d+)?$/.test(a)},digits:function(a,b){return this.optional(b)||/^\d+$/.test(a)},creditcard:function(a,b){if(this.optional(b))return"dependency-mismatch";if(/[^0-9-]+/.test(a))return false;var d=0,e=0,f=false;a=a.replace(/\D/g,"");for(var g=a.length-1;g>=
0;g--){e=a.charAt(g);e=parseInt(e,10);if(f)if((e*=2)>9)e-=9;d+=e;f=!f}return d%10==0},accept:function(a,b,d){d=typeof d=="string"?d.replace(/,/g,"|"):"png|jpe?g|gif";return this.optional(b)||a.match(RegExp(".("+d+")$","i"))},equalTo:function(a,b,d){d=c(d).unbind(".validate-equalTo").bind("blur.validate-equalTo",function(){c(b).valid()});return a==d.val()}}});c.format=c.validator.format})(jQuery);
(function(c){var a={};if(c.ajaxPrefilter)c.ajaxPrefilter(function(d,e,f){e=d.port;if(d.mode=="abort"){a[e]&&a[e].abort();a[e]=f}});else{var b=c.ajax;c.ajax=function(d){var e=("port"in d?d:c.ajaxSettings).port;if(("mode"in d?d:c.ajaxSettings).mode=="abort"){a[e]&&a[e].abort();return a[e]=b.apply(this,arguments)}return b.apply(this,arguments)}}})(jQuery);
(function(c){!jQuery.event.special.focusin&&!jQuery.event.special.focusout&&document.addEventListener&&c.each({focus:"focusin",blur:"focusout"},function(a,b){function d(e){e=c.event.fix(e);e.type=b;return c.event.handle.call(this,e)}c.event.special[b]={setup:function(){this.addEventListener(a,d,true)},teardown:function(){this.removeEventListener(a,d,true)},handler:function(e){arguments[0]=c.event.fix(e);arguments[0].type=b;return c.event.handle.apply(this,arguments)}}});c.extend(c.fn,{validateDelegate:function(a,
b,d){return this.bind(b,function(e){var f=c(e.target);if(f.is(a))return d.apply(f,arguments)})}})})(jQuery);

//tablesorter
(function(c){c.extend({tablesorter:new function(){function a(b,h){i(b+","+((new Date).getTime()-h.getTime())+"ms")}function i(b){typeof console!="undefined"&&typeof console.debug!="undefined"?console.log(b):alert(b)}function m(b,h){if(b.config.debug)var a="";if(b.tBodies.length!=0){var e=b.tBodies[0].rows;if(e[0])for(var f=[],p=e[0].cells.length,j=0;j<p;j++){var k=!1;c.metadata&&c(h[j]).metadata()&&c(h[j]).metadata().sorter?k=l(c(h[j]).metadata().sorter):b.config.headers[j]&&b.config.headers[j].sorter&&
(k=l(b.config.headers[j].sorter));if(!k)a:{for(var k=b,g=e,n=-1,m=j,t=q.length,u=!1,o=!1,r=!0;o==""&&r;)n++,g[n]?(u=g[n].cells[m],o=c.trim(v(k.config,u)),k.config.debug&&i("Checking if value was empty on row:"+n)):r=!1;for(g=1;g<t;g++)if(q[g].is(o,k,u)){k=q[g];break a}k=q[0]}b.config.debug&&(a+="column:"+j+" parser:"+k.id+"\n");f.push(k)}b.config.debug&&i(a);return f}}function l(b){for(var h=q.length,a=0;a<h;a++)if(q[a].id.toLowerCase()==b.toLowerCase())return q[a];return!1}function o(b){if(b.config.debug)var h=
new Date;for(var d=b.tBodies[0]&&b.tBodies[0].rows.length||0,e=b.tBodies[0].rows[0]&&b.tBodies[0].rows[0].cells.length||0,f=b.config.parsers,p={row:[],normalized:[]},j=0;j<d;++j){var k=c(b.tBodies[0].rows[j]),g=[];if(k.hasClass(b.config.cssChildRow))p.row[p.row.length-1]=p.row[p.row.length-1].add(k);else{p.row.push(k);for(var n=0;n<e;++n)g.push(f[n].format(v(b.config,k[0].cells[n]),b,k[0].cells[n]));g.push(p.normalized.length);p.normalized.push(g)}}b.config.debug&&a("Building cache for "+d+" rows:",
h);return p}function v(b,a){var d="";if(!a)return"";if(!b.supportsTextContent)b.supportsTextContent=a.textContent||!1;return d=b.textExtraction=="simple"?b.supportsTextContent?a.textContent:a.childNodes[0]&&a.childNodes[0].hasChildNodes()?a.childNodes[0].innerHTML:a.innerHTML:typeof b.textExtraction=="function"?b.textExtraction(a):c(a).text()}function w(b,h){if(b.config.debug)var d=new Date;for(var e=h.row,f=h.normalized,p=f.length,j=f[0].length-1,k=c(b.tBodies[0]),g=[],n=0;n<p;n++){var m=f[n][j];
g.push(e[m]);if(!b.config.appender)for(var t=e[m].length,i=0;i<t;i++)k[0].appendChild(e[m][i])}b.config.appender&&b.config.appender(b,g);g=null;b.config.debug&&a("Rebuilt table:",d);x(b);setTimeout(function(){c(b).trigger("sortEnd")},0)}function C(b){if(b.config.debug)var h=new Date;var d=D(b);$tableHeaders=c(b.config.selectorHeaders,b).each(function(a){this.column=d[this.parentNode.rowIndex+"-"+this.cellIndex];this.count=this.order=typeof b.config.sortInitialOrder!="Number"?b.config.sortInitialOrder.toLowerCase()==
"desc"?1:0:b.config.sortInitialOrder==1?1:0;var h;h=c.metadata&&c(this).metadata().sorter===!1?!0:!1;h||(h=b.config.headers[a]&&b.config.headers[a].sorter===!1?!0:!1);if(h)this.sortDisabled=!0;if(y(b,a))this.order=this.lockedOrder=y(b,a);this.sortDisabled||(h=c(this).addClass(b.config.cssHeader),b.config.onRenderHeader&&b.config.onRenderHeader.apply(h));b.config.headerList[a]=this});b.config.debug&&(a("Built headers:",h),i($tableHeaders));return $tableHeaders}function D(b){for(var a=[],d={},b=b.getElementsByTagName("THEAD")[0].getElementsByTagName("TR"),
e=0;e<b.length;e++)for(var c=b[e].cells,p=0;p<c.length;p++){var j=c[p],k=j.parentNode.rowIndex,g=k+"-"+j.cellIndex,n=j.rowSpan||1,j=j.colSpan||1,m;typeof a[k]=="undefined"&&(a[k]=[]);for(var i=0;i<a[k].length+1;i++)if(typeof a[k][i]=="undefined"){m=i;break}d[g]=m;for(i=k;i<k+n;i++){typeof a[i]=="undefined"&&(a[i]=[]);for(var g=a[i],l=m;l<m+j;l++)g[l]="x"}}return d}function y(b,a){if(b.config.headers[a]&&b.config.headers[a].lockedOrder)return b.config.headers[a].lockedOrder;return!1}function x(b){for(var a=
b.config.widgets,d=a.length,c=0;c<d;c++)z(a[c]).format(b)}function z(b){for(var a=r.length,c=0;c<a;c++)if(r[c].id.toLowerCase()==b.toLowerCase())return r[c]}function E(b,a){for(var c=a.length,e=0;e<c;e++)if(a[e][0]==b)return!0;return!1}function A(b,a,d,e){a.removeClass(e[0]).removeClass(e[1]);var f=[];a.each(function(){this.sortDisabled||(f[this.column]=c(this))});b=d.length;for(a=0;a<b;a++)f[d[a][0]].addClass(e[d[a][1]])}function F(a){if(a.config.widthFixed){var h=c("<colgroup>");c("tr:first td",
a.tBodies[0]).each(function(){h.append(c("<col>").css("width",c(this).width()))});c(a).prepend(h)}}function B(b,c,d){if(b.config.debug)var e=new Date;for(var f="var sortWrapper = function(a,b) {",i=c.length,j=0;j<i;j++){var k=c[j][0],g=c[j][1],k=b.config.parsers[k].type=="text"?g==0?s("text","asc",k):s("text","desc",k):g==0?s("numeric","asc",k):s("numeric","desc",k),n="e"+j;f+="var "+n+" = "+k;f+="if("+n+") { return "+n+"; } ";f+="else { "}j=d.normalized[0].length-1;f+="return a["+j+"]-b["+j+"];";
for(j=0;j<i;j++)f+="}; ";f+="return 0; ";f+="}; ";b.config.debug&&a("Evaling expression:"+f,new Date);eval(f);d.normalized.sort(sortWrapper);b.config.debug&&a("Sorting on "+c.toString()+" and dir "+g+" time:",e);return d}function s(a,c,d){var e="a["+d+"]",d="b["+d+"]";if(a=="text"&&c=="asc")return"("+e+" == "+d+" ? 0 : ("+e+" === null ? Number.POSITIVE_INFINITY : ("+d+" === null ? Number.NEGATIVE_INFINITY : ("+e+" < "+d+") ? -1 : 1 )));";else if(a=="text"&&c=="desc")return"("+e+" == "+d+" ? 0 : ("+
e+" === null ? Number.POSITIVE_INFINITY : ("+d+" === null ? Number.NEGATIVE_INFINITY : ("+d+" < "+e+") ? -1 : 1 )));";else if(a=="numeric"&&c=="asc")return"("+e+" === null && "+d+" === null) ? 0 :("+e+" === null ? Number.POSITIVE_INFINITY : ("+d+" === null ? Number.NEGATIVE_INFINITY : "+e+" - "+d+"));";else if(a=="numeric"&&c=="desc")return"("+e+" === null && "+d+" === null) ? 0 :("+e+" === null ? Number.POSITIVE_INFINITY : ("+d+" === null ? Number.NEGATIVE_INFINITY : "+d+" - "+e+"));"}var q=[],r=
[];this.defaults={cssHeader:"header",cssAsc:"headerSortUp",cssDesc:"headerSortDown",cssChildRow:"expand-child",sortInitialOrder:"asc",sortMultiSortKey:"shiftKey",sortForce:null,sortAppend:null,sortLocaleCompare:!0,textExtraction:"simple",parsers:{},widgets:[],widgetZebra:{css:["even","odd"]},headers:{},widthFixed:!1,cancelSelection:!0,sortList:[],headerList:[],dateFormat:"us",decimal:"/.|,/g",onRenderHeader:null,selectorHeaders:"thead th",debug:!1};this.benchmark=a;this.construct=function(a){return this.each(function(){if(this.tHead&&
this.tBodies){var h,d,e,f;this.config={};f=c.extend(this.config,c.tablesorter.defaults,a);h=c(this);c.data(this,"tablesorter",f);d=C(this);this.config.parsers=m(this,d);e=o(this);var i=[f.cssDesc,f.cssAsc];F(this);d.click(function(a){var b=h[0].tBodies[0]&&h[0].tBodies[0].rows.length||0;if(!this.sortDisabled&&b>0){h.trigger("sortStart");c(this);b=this.column;this.order=this.count++%2;if(this.lockedOrder)this.order=this.lockedOrder;if(a[f.sortMultiSortKey])if(E(b,f.sortList))for(a=0;a<f.sortList.length;a++){var g=
f.sortList[a],n=f.headerList[g[0]];if(g[0]==b)n.count=g[1],n.count++,g[1]=n.count%2}else f.sortList.push([b,this.order]);else{f.sortList=[];if(f.sortForce!=null){g=f.sortForce;for(a=0;a<g.length;a++)g[a][0]!=b&&f.sortList.push(g[a])}f.sortList.push([b,this.order])}setTimeout(function(){A(h[0],d,f.sortList,i);w(h[0],B(h[0],f.sortList,e))},1);return!1}}).mousedown(function(){if(f.cancelSelection)return this.onselectstart=function(){return!1},!1});h.bind("update",function(){var a=this;setTimeout(function(){a.config.parsers=
m(a,d);e=o(a)},1)}).bind("updateCell",function(a,b){var c=this.config,d=[b.parentNode.rowIndex-1,b.cellIndex];e.normalized[d[0]][d[1]]=c.parsers[d[1]].format(v(c,b),b)}).bind("sorton",function(a,b){c(this).trigger("sortStart");f.sortList=b;for(var g=f.sortList,h=this.config,m=g.length,l=0;l<m;l++){var o=g[l],q=h.headerList[o[0]];q.count=o[1];q.count++}A(this,d,g,i);w(this,B(this,g,e))}).bind("appendCache",function(){w(this,e)}).bind("applyWidgetId",function(a,b){z(b).format(this)}).bind("applyWidgets",
function(){x(this)});if(c.metadata&&c(this).metadata()&&c(this).metadata().sortlist)f.sortList=c(this).metadata().sortlist;f.sortList.length>0&&h.trigger("sorton",[f.sortList]);x(this)}})};this.addParser=function(a){for(var c=q.length,d=!0,e=0;e<c;e++)q[e].id.toLowerCase()==a.id.toLowerCase()&&(d=!1);d&&q.push(a)};this.addWidget=function(a){r.push(a)};this.formatFloat=function(a){a=parseFloat(a);return isNaN(a)?0:a};this.formatInt=function(a){a=parseInt(a);return isNaN(a)?0:a};this.isDigit=function(a){return/^[-+]?\d*$/.test(c.trim(a.replace(/[,.']/g,
"")))};this.clearTableBody=function(a){c.browser.msie?function(){for(;this.firstChild;)this.removeChild(this.firstChild)}.apply(a.tBodies[0]):a.tBodies[0].innerHTML=""}}});c.fn.extend({tablesorter:c.tablesorter.construct});var l=c.tablesorter;l.addParser({id:"text",is:function(){return!0},format:function(a){return c.trim(a.toLocaleLowerCase())},type:"text"});l.addParser({id:"digit",is:function(a,i){return c.tablesorter.isDigit(a,i.config)},format:function(a){return c.tablesorter.formatFloat(a)},type:"numeric"});
l.addParser({id:"currency",is:function(a){return/^[\u00a3$\u20ac?.]/.test(a)},format:function(a){return c.tablesorter.formatFloat(a.replace(RegExp(/[\u00a3$\u20ac]/g),""))},type:"numeric"});l.addParser({id:"ipAddress",is:function(a){return/^\d{2,3}[\.]\d{2,3}[\.]\d{2,3}[\.]\d{2,3}$/.test(a)},format:function(a){for(var a=a.split("."),i="",m=a.length,l=0;l<m;l++){var o=a[l];i+=o.length==2?"0"+o:o}return c.tablesorter.formatFloat(i)},type:"numeric"});l.addParser({id:"url",is:function(a){return/^(https?|ftp|file):\/\/$/.test(a)},
format:function(a){return jQuery.trim(a.replace(RegExp(/(https?|ftp|file):\/\//),""))},type:"text"});l.addParser({id:"isoDate",is:function(a){return/^\d{4}[\/-]\d{1,2}[\/-]\d{1,2}$/.test(a)},format:function(a){return c.tablesorter.formatFloat(a!=""?(new Date(a.replace(RegExp(/-/g),"/"))).getTime():"0")},type:"numeric"});l.addParser({id:"percent",is:function(a){return/\%$/.test(c.trim(a))},format:function(a){return c.tablesorter.formatFloat(a.replace(RegExp(/%/g),""))},type:"numeric"});l.addParser({id:"usLongDate",
is:function(a){return a.match(RegExp(/^[A-Za-z]{3,10}\.? [0-9]{1,2}, ([0-9]{4}|'?[0-9]{2}) (([0-2]?[0-9]:[0-5][0-9])|([0-1]?[0-9]:[0-5][0-9]\s(AM|PM)))$/))},format:function(a){return c.tablesorter.formatFloat((new Date(a)).getTime())},type:"numeric"});l.addParser({id:"shortDate",is:function(a){return/\d{1,2}[\/\-]\d{1,2}[\/\-]\d{2,4}/.test(a)},format:function(a,i){var m=i.config,a=a.replace(/\-/g,"/");if(m.dateFormat=="us")a=a.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/,"$3/$1/$2");else if(m.dateFormat==
"uk")a=a.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/,"$3/$2/$1");else if(m.dateFormat=="dd/mm/yy"||m.dateFormat=="dd-mm-yy")a=a.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2})/,"$1/$2/$3");return c.tablesorter.formatFloat((new Date(a)).getTime())},type:"numeric"});l.addParser({id:"time",is:function(a){return/^(([0-2]?[0-9]:[0-5][0-9])|([0-1]?[0-9]:[0-5][0-9]\s(am|pm)))$/.test(a)},format:function(a){return c.tablesorter.formatFloat((new Date("2000/01/01 "+a)).getTime())},type:"numeric"});l.addParser({id:"metadata",
is:function(){return!1},format:function(a,i,m){a=i.config;a=!a.parserMetadataName?"sortValue":a.parserMetadataName;return c(m).metadata()[a]},type:"numeric"});l.addWidget({id:"zebra",format:function(a){if(a.config.debug)var i=new Date;var m,l=-1,o;c("tr:visible",a.tBodies[0]).each(function(){m=c(this);m.hasClass(a.config.cssChildRow)||l++;o=l%2==0;m.removeClass(a.config.widgetZebra.css[o?0:1]).addClass(a.config.widgetZebra.css[o?1:0])});a.config.debug&&c.tablesorter.benchmark("Applying Zebra widget",
i)}})})(jQuery);

//datetimepicker
(function(d){function l(){this.regional=[];this.regional[""]={currentText:"Now",closeText:"Done",ampm:!1,timeFormat:"hh:mm tt",timeOnlyTitle:"Choose Time",timeText:"Time",hourText:"Hour",minuteText:"Minute",secondText:"Second",timezoneText:"Time Zone"};this._defaults={showButtonPanel:!0,timeOnly:!1,showHour:!0,showMinute:!0,showSecond:!1,showTimezone:!1,showTime:!0,stepHour:0.05,stepMinute:0.05,stepSecond:0.05,hour:0,minute:0,second:0,timezone:"+0000",hourMin:0,minuteMin:0,secondMin:0,hourMax:23,
minuteMax:59,secondMax:59,minDateTime:null,maxDateTime:null,hourGrid:0,minuteGrid:0,secondGrid:0,alwaysSetTime:!0,separator:" ",altFieldTimeOnly:!0,showTimepicker:!0,timezoneList:["-1100","-1000","-0900","-0800","-0700","-0600","-0500","-0400","-0300","-0200","-0100","+0000","+0100","+0200","+0300","+0400","+0500","+0600","+0700","+0800","+0900","+1000","+1100","+1200"]};d.extend(this._defaults,this.regional[""])}d.extend(d.ui,{timepicker:{version:"0.9.5"}});d.extend(l.prototype,{$input:null,$altInput:null,
$timeObj:null,inst:null,hour_slider:null,minute_slider:null,second_slider:null,timezone_select:null,hour:0,minute:0,second:0,timezone:"+0000",hourMinOriginal:null,minuteMinOriginal:null,secondMinOriginal:null,hourMaxOriginal:null,minuteMaxOriginal:null,secondMaxOriginal:null,ampm:"",formattedDate:"",formattedTime:"",formattedDateTime:"",timezoneList:["-1100","-1000","-0900","-0800","-0700","-0600","-0500","-0400","-0300","-0200","-0100","+0000","+0100","+0200","+0300","+0400","+0500","+0600","+0700",
"+0800","+0900","+1000","+1100","+1200"],setDefaults:function(b){var a=this._defaults,b=b||{};d.extend(a,b);for(var c in b)if(b[c]===null||b[c]===void 0)a[c]=b[c];return this},_newInst:function(b,a){var c=new l,e={},g;for(g in this._defaults){var h=b.attr("time:"+g);if(h)try{e[g]=eval(h)}catch(f){e[g]=h}}c._defaults=d.extend({},this._defaults,e,a,{beforeShow:function(b,e){d.isFunction(a.beforeShow)&&a.beforeShow(b,e,c)},onChangeMonthYear:function(e,g,f){c._updateDateTime(f);d.isFunction(a.onChangeMonthYear)&&
a.onChangeMonthYear.call(b[0],e,g,f,c)},onClose:function(e,g){c.timeDefined===!0&&b.val()!=""&&c._updateDateTime(g);d.isFunction(a.onClose)&&a.onClose.call(b[0],e,g,c)},timepicker:c});c.hour=c._defaults.hour;c.minute=c._defaults.minute;c.second=c._defaults.second;c.ampm="";c.$input=b;if(a.altField)c.$altInput=d(a.altField).css({cursor:"pointer"}).focus(function(){b.trigger("focus")});if(c._defaults.minDate!==void 0&&c._defaults.minDate instanceof Date)c._defaults.minDateTime=new Date(c._defaults.minDate.getTime());
if(c._defaults.minDateTime!==void 0&&c._defaults.minDateTime instanceof Date)c._defaults.minDate=new Date(c._defaults.minDateTime.getTime());if(c._defaults.maxDate!==void 0&&c._defaults.maxDate instanceof Date)c._defaults.maxDateTime=new Date(c._defaults.maxDate.getTime());if(c._defaults.maxDateTime!==void 0&&c._defaults.maxDateTime instanceof Date)c._defaults.maxDate=new Date(c._defaults.maxDateTime.getTime());return c},_addTimePicker:function(b){this.timeDefined=this._parseTime(this.$altInput&&
this._defaults.altFieldTimeOnly?this.$input.val()+" "+this.$altInput.val():this.$input.val());this._limitMinMaxDateTime(b,!1);this._injectTimePicker()},_parseTime:function(b,a){var c=this._defaults.timeFormat.toString().replace(/h{1,2}/ig,"(\\d?\\d)").replace(/m{1,2}/ig,"(\\d?\\d)").replace(/s{1,2}/ig,"(\\d?\\d)").replace(/t{1,2}/ig,"(am|pm|a|p)?").replace(/z{1}/ig,"((\\+|-)\\d\\d\\d\\d)?").replace(/\s/g,"\\s?")+"$",e=this._getFormatPositions();if(!this.inst)this.inst=d.datepicker._getInst(this.$input[0]);
if(a||!this._defaults.timeOnly)c=".{"+d.datepicker._get(this.inst,"dateFormat").length+",}"+this._defaults.separator.replace(RegExp("[.*+?|()\\[\\]{}\\\\]","g"),"\\$&")+c;if(c=b.match(RegExp(c,"i"))){if(e.t!==-1)this.ampm=(c[e.t]===void 0||c[e.t].length===0?"":c[e.t].charAt(0).toUpperCase()=="A"?"AM":"PM").toUpperCase();if(e.h!==-1)this.hour=this.ampm=="AM"&&c[e.h]=="12"?0:this.ampm=="PM"&&c[e.h]!="12"?(parseFloat(c[e.h])+12).toFixed(0):Number(c[e.h]);if(e.m!==-1)this.minute=Number(c[e.m]);if(e.s!==
-1)this.second=Number(c[e.s]);if(e.z!==-1)this.timezone=c[e.z];return!0}return!1},_getFormatPositions:function(){var b=this._defaults.timeFormat.toLowerCase().match(/(h{1,2}|m{1,2}|s{1,2}|t{1,2}|z)/g),a={h:-1,m:-1,s:-1,t:-1,z:-1};if(b)for(var c=0;c<b.length;c++)a[b[c].toString().charAt(0)]==-1&&(a[b[c].toString().charAt(0)]=c+1);return a},_injectTimePicker:function(){var b=this.inst.dpDiv,a=this._defaults,c=this,e=(a.hourMax-a.hourMax%a.stepHour).toFixed(0),g=(a.minuteMax-a.minuteMax%a.stepMinute).toFixed(0),
h=(a.secondMax-a.secondMax%a.stepSecond).toFixed(0),f=this.inst.id.toString().replace(/([^A-Za-z0-9_])/g,"");if(b.find("div#ui-timepicker-div-"+f).length===0&&a.showTimepicker){var i='<div class="ui-timepicker-div" id="ui-timepicker-div-'+f+'"><dl><dt class="ui_tpicker_time_label" id="ui_tpicker_time_label_'+f+'"'+(a.showTime?"":' style="display:none;"')+">"+a.timeText+'</dt><dd class="ui_tpicker_time" id="ui_tpicker_time_'+f+'"'+(a.showTime?"":' style="display:none;"')+'></dd><dt class="ui_tpicker_hour_label" id="ui_tpicker_hour_label_'+
f+'"'+(a.showHour?"":' style="display:none;"')+">"+a.hourText+"</dt>",n=0,o=0,l=0,k;if(a.showHour&&a.hourGrid>0){i+='<dd class="ui_tpicker_hour"><div id="ui_tpicker_hour_'+f+'"'+(a.showHour?"":' style="display:none;"')+'></div><div style="padding-left: 1px"><table><tr>';for(var j=a.hourMin;j<e;j+=a.hourGrid){n++;var m=a.ampm&&j>12?j-12:j;m<10&&(m="0"+m);a.ampm&&(j==0?m="12a":m+=j<12?"a":"p");i+="<td>"+m+"</td>"}i+="</tr></table></div></dd>"}else i+='<dd class="ui_tpicker_hour" id="ui_tpicker_hour_'+
f+'"'+(a.showHour?"":' style="display:none;"')+"></dd>";i+='<dt class="ui_tpicker_minute_label" id="ui_tpicker_minute_label_'+f+'"'+(a.showMinute?"":' style="display:none;"')+">"+a.minuteText+"</dt>";if(a.showMinute&&a.minuteGrid>0){i+='<dd class="ui_tpicker_minute ui_tpicker_minute_'+a.minuteGrid+'"><div id="ui_tpicker_minute_'+f+'"'+(a.showMinute?"":' style="display:none;"')+'></div><div style="padding-left: 1px"><table><tr>';for(j=a.minuteMin;j<g;j+=a.minuteGrid)o++,i+="<td>"+(j<10?"0":"")+j+"</td>";
i+="</tr></table></div></dd>"}else i+='<dd class="ui_tpicker_minute" id="ui_tpicker_minute_'+f+'"'+(a.showMinute?"":' style="display:none;"')+"></dd>";i+='<dt class="ui_tpicker_second_label" id="ui_tpicker_second_label_'+f+'"'+(a.showSecond?"":' style="display:none;"')+">"+a.secondText+"</dt>";if(a.showSecond&&a.secondGrid>0){i+='<dd class="ui_tpicker_second ui_tpicker_second_'+a.secondGrid+'"><div id="ui_tpicker_second_'+f+'"'+(a.showSecond?"":' style="display:none;"')+'></div><div style="padding-left: 1px"><table><tr>';
for(j=a.secondMin;j<h;j+=a.secondGrid)l++,i+="<td>"+(j<10?"0":"")+j+"</td>";i+="</tr></table></div></dd>"}else i+='<dd class="ui_tpicker_second" id="ui_tpicker_second_'+f+'"'+(a.showSecond?"":' style="display:none;"')+"></dd>";i+='<dt class="ui_tpicker_timezone_label" id="ui_tpicker_timezone_label_'+f+'"'+(a.showTimezone?"":' style="display:none;"')+">"+a.timezoneText+"</dt>";i+='<dd class="ui_tpicker_timezone" id="ui_tpicker_timezone_'+f+'"'+(a.showTimezone?"":' style="display:none;"')+"></dd>";
i+="</dl></div>";$tp=d(i);a.timeOnly===!0&&($tp.prepend('<div class="ui-widget-header ui-helper-clearfix ui-corner-all"><div class="ui-datepicker-title">'+a.timeOnlyTitle+"</div></div>"),b.find(".ui-datepicker-header, .ui-datepicker-calendar").hide());this.hour_slider=$tp.find("#ui_tpicker_hour_"+f).slider({orientation:"horizontal",value:this.hour,min:a.hourMin,max:e,step:a.stepHour,slide:function(a,b){c.hour_slider.slider("option","value",b.value);c._onTimeChange()}});this.minute_slider=$tp.find("#ui_tpicker_minute_"+
f).slider({orientation:"horizontal",value:this.minute,min:a.minuteMin,max:g,step:a.stepMinute,slide:function(a,b){c.minute_slider.slider("option","value",b.value);c._onTimeChange()}});this.second_slider=$tp.find("#ui_tpicker_second_"+f).slider({orientation:"horizontal",value:this.second,min:a.secondMin,max:h,step:a.stepSecond,slide:function(a,b){c.second_slider.slider("option","value",b.value);c._onTimeChange()}});this.timezone_select=$tp.find("#ui_tpicker_timezone_"+f).append("<select></select>").find("select");
d.fn.append.apply(this.timezone_select,d.map(a.timezoneList,function(a){return d("<option />").val(typeof a=="object"?a.value:a).text(typeof a=="object"?a.label:a)}));this.timezone_select.val(typeof this.timezone!="undefined"&&this.timezone!=null&&this.timezone!=""?this.timezone:a.timezone);this.timezone_select.change(function(){c._onTimeChange()});a.showHour&&a.hourGrid>0&&(k=100*n*a.hourGrid/(e-a.hourMin),$tp.find(".ui_tpicker_hour table").css({width:k+"%",marginLeft:k/(-2*n)+"%",borderCollapse:"collapse"}).find("td").each(function(){d(this).click(function(){var b=
d(this).html();if(a.ampm)var e=b.substring(2).toLowerCase(),b=parseInt(b.substring(0,2)),b=e=="a"?b==12?0:b:b==12?12:b+12;c.hour_slider.slider("option","value",b);c._onTimeChange();c._onSelectHandler()}).css({cursor:"pointer",width:100/n+"%",textAlign:"center",overflow:"hidden"})}));a.showMinute&&a.minuteGrid>0&&(k=100*o*a.minuteGrid/(g-a.minuteMin),$tp.find(".ui_tpicker_minute table").css({width:k+"%",marginLeft:k/(-2*o)+"%",borderCollapse:"collapse"}).find("td").each(function(){d(this).click(function(){c.minute_slider.slider("option",
"value",d(this).html());c._onTimeChange();c._onSelectHandler()}).css({cursor:"pointer",width:100/o+"%",textAlign:"center",overflow:"hidden"})}));a.showSecond&&a.secondGrid>0&&$tp.find(".ui_tpicker_second table").css({width:k+"%",marginLeft:k/(-2*l)+"%",borderCollapse:"collapse"}).find("td").each(function(){d(this).click(function(){c.second_slider.slider("option","value",d(this).html());c._onTimeChange();c._onSelectHandler()}).css({cursor:"pointer",width:100/l+"%",textAlign:"center",overflow:"hidden"})});
e=b.find(".ui-datepicker-buttonpane");e.length?e.before($tp):b.append($tp);this.$timeObj=$tp.find("#ui_tpicker_time_"+f);if(this.inst!==null)b=this.timeDefined,this._onTimeChange(),this.timeDefined=b;b=function(){c._onSelectHandler()};this.hour_slider.bind("slidestop",b);this.minute_slider.bind("slidestop",b);this.second_slider.bind("slidestop",b)}},_limitMinMaxDateTime:function(b,a){var c=this._defaults,e=new Date(b.selectedYear,b.selectedMonth,b.selectedDay);if(this._defaults.showTimepicker){if(this._defaults.minDateTime!==
null&&e){var d=this._defaults.minDateTime,h=new Date(d.getFullYear(),d.getMonth(),d.getDate(),0,0,0,0);if(this.hourMinOriginal===null||this.minuteMinOriginal===null||this.secondMinOriginal===null)this.hourMinOriginal=c.hourMin,this.minuteMinOriginal=c.minuteMin,this.secondMinOriginal=c.secondMin;if(b.settings.timeOnly||h.getTime()==e.getTime())if(this._defaults.hourMin=d.getHours(),this.hour<=this._defaults.hourMin)if(this.hour=this._defaults.hourMin,this._defaults.minuteMin=d.getMinutes(),this.minute<=
this._defaults.minuteMin)this.minute=this._defaults.minuteMin,this._defaults.secondMin=d.getSeconds();else{if(this.second<this._defaults.secondMin)this.second=this._defaults.secondMin;this._defaults.secondMin=this.secondMinOriginal}else this._defaults.minuteMin=this.minuteMinOriginal,this._defaults.secondMin=this.secondMinOriginal;else this._defaults.hourMin=this.hourMinOriginal,this._defaults.minuteMin=this.minuteMinOriginal,this._defaults.secondMin=this.secondMinOriginal}if(this._defaults.maxDateTime!==
null&&e){d=this._defaults.maxDateTime;h=new Date(d.getFullYear(),d.getMonth(),d.getDate(),0,0,0,0);if(this.hourMaxOriginal===null||this.minuteMaxOriginal===null||this.secondMaxOriginal===null)this.hourMaxOriginal=c.hourMax,this.minuteMaxOriginal=c.minuteMax,this.secondMaxOriginal=c.secondMax;if(b.settings.timeOnly||h.getTime()==e.getTime())if(this._defaults.hourMax=d.getHours(),this.hour>=this._defaults.hourMax)if(this.hour=this._defaults.hourMax,this._defaults.minuteMax=d.getMinutes(),this.minute>=
this._defaults.minuteMax)this.minute=this._defaults.minuteMax,this._defaults.secondMin=d.getSeconds();else{if(this.second>this._defaults.secondMax)this.second=this._defaults.secondMax;this._defaults.secondMax=this.secondMaxOriginal}else this._defaults.minuteMax=this.minuteMaxOriginal,this._defaults.secondMax=this.secondMaxOriginal;else this._defaults.hourMax=this.hourMaxOriginal,this._defaults.minuteMax=this.minuteMaxOriginal,this._defaults.secondMax=this.secondMaxOriginal}a!==void 0&&a===!0&&(this.hour_slider.slider("option",
{min:this._defaults.hourMin,max:this._defaults.hourMax}).slider("value",this.hour),this.minute_slider.slider("option",{min:this._defaults.minuteMin,max:this._defaults.minuteMax}).slider("value",this.minute),this.second_slider.slider("option",{min:this._defaults.secondMin,max:this._defaults.secondMax}).slider("value",this.second))}},_onTimeChange:function(){var b=this.hour_slider?this.hour_slider.slider("value"):!1,a=this.minute_slider?this.minute_slider.slider("value"):!1,c=this.second_slider?this.second_slider.slider("value"):
!1,e=this.timezone_select?this.timezone_select.val():!1;b!==!1&&(b=parseInt(b,10));a!==!1&&(a=parseInt(a,10));c!==!1&&(c=parseInt(c,10));var d=b<12?"AM":"PM",h=b!=this.hour||a!=this.minute||c!=this.second||this.ampm.length>0&&this.ampm!=d||e!=this.timezone;if(h){if(b!==!1)this.hour=b;if(a!==!1)this.minute=a;if(c!==!1)this.second=c;if(e!==!1)this.timezone=e;this._limitMinMaxDateTime(this.inst,!0)}if(this._defaults.ampm)this.ampm=d;this._formatTime();this.$timeObj&&this.$timeObj.text(this.formattedTime);
this.timeDefined=!0;h&&this._updateDateTime()},_onSelectHandler:function(){var b=this._defaults.onSelect,a=this.$input?this.$input[0]:null;b&&a&&b.apply(a,[this.formattedDateTime,this])},_formatTime:function(b,a,c){if(c==void 0)c=this._defaults.ampm;var b=b||{hour:this.hour,minute:this.minute,second:this.second,ampm:this.ampm,timezone:this.timezone},e=a||this._defaults.timeFormat.toString();if(c)var g=b.ampm=="AM"?b.hour:b.hour%12,g=Number(g)===0?12:g,e=e.toString().replace(/hh/g,(g<10?"0":"")+g).replace(/h/g,
g).replace(/mm/g,(b.minute<10?"0":"")+b.minute).replace(/m/g,b.minute).replace(/ss/g,(b.second<10?"0":"")+b.second).replace(/s/g,b.second).replace(/TT/g,b.ampm.toUpperCase()).replace(/Tt/g,b.ampm.toUpperCase()).replace(/tT/g,b.ampm.toLowerCase()).replace(/tt/g,b.ampm.toLowerCase()).replace(/T/g,b.ampm.charAt(0).toUpperCase()).replace(/t/g,b.ampm.charAt(0).toLowerCase()).replace(/z/g,b.timezone);else e=e.toString().replace(/hh/g,(b.hour<10?"0":"")+b.hour).replace(/h/g,b.hour).replace(/mm/g,(b.minute<
10?"0":"")+b.minute).replace(/m/g,b.minute).replace(/ss/g,(b.second<10?"0":"")+b.second).replace(/s/g,b.second).replace(/z/g,b.timezone),e=d.trim(e.replace(/t/gi,""));if(arguments.length)return e;else this.formattedTime=e},_updateDateTime:function(b){b=this.inst||b;dt=new Date(b.selectedYear,b.selectedMonth,b.selectedDay);dateFmt=d.datepicker._get(b,"dateFormat");formatCfg=d.datepicker._getFormatConfig(b);timeAvailable=dt!==null&&this.timeDefined;var a=this.formattedDate=d.datepicker.formatDate(dateFmt,
dt===null?new Date:dt,formatCfg);if(!(b.lastVal!==void 0&&b.lastVal.length>0&&this.$input.val().length===0)){if(this._defaults.timeOnly===!0)a=this.formattedTime;else if(this._defaults.timeOnly!==!0&&(this._defaults.alwaysSetTime||timeAvailable))a+=this._defaults.separator+this.formattedTime;this.formattedDateTime=a;this._defaults.showTimepicker?this.$altInput&&this._defaults.altFieldTimeOnly===!0?(this.$altInput.val(this.formattedTime),this.$input.val(this.formattedDate)):(this.$altInput&&this.$altInput.val(a),
this.$input.val(a)):this.$input.val(this.formattedDate);this.$input.trigger("change")}}});d.fn.extend({timepicker:function(b){var b=b||{},a=arguments;typeof b=="object"&&(a[0]=d.extend(b,{timeOnly:!0}));return d(this).each(function(){d.fn.datetimepicker.apply(d(this),a)})},datetimepicker:function(b){var b=b||{},a=arguments;return typeof b=="string"?b=="getDate"?d.fn.datepicker.apply(d(this[0]),a):this.each(function(){var b=d(this);b.datepicker.apply(b,a)}):this.each(function(){var a=d(this);a.datepicker(d.timepicker._newInst(a,
b)._defaults)})}});d.datepicker._base_selectDate=d.datepicker._selectDate;d.datepicker._selectDate=function(b,a){var c=this._getInst(d(b)[0]),e=this._get(c,"timepicker");e?(e._limitMinMaxDateTime(c,!0),c.inline=c.stay_open=!0,this._base_selectDate(b,a+e._defaults.separator+e.formattedTime),c.inline=c.stay_open=!1,this._notifyChange(c),this._updateDatepicker(c)):this._base_selectDate(b,a)};d.datepicker._base_updateDatepicker=d.datepicker._updateDatepicker;d.datepicker._updateDatepicker=function(b){if(typeof b.stay_open!==
"boolean"||b.stay_open===!1){this._base_updateDatepicker(b);var a=this._get(b,"timepicker");a&&a._addTimePicker(b)}};d.datepicker._base_doKeyPress=d.datepicker._doKeyPress;d.datepicker._doKeyPress=function(b){var a=d.datepicker._getInst(b.target),c=d.datepicker._get(a,"timepicker");if(c&&d.datepicker._get(a,"constrainInput")){var e=c._defaults.ampm,a=c._defaults.timeFormat.toString().replace(/[hms]/g,"").replace(/TT/g,e?"APM":"").replace(/Tt/g,e?"AaPpMm":"").replace(/tT/g,e?"AaPpMm":"").replace(/T/g,
e?"AP":"").replace(/tt/g,e?"apm":"").replace(/t/g,e?"ap":"")+" "+c._defaults.separator+d.datepicker._possibleChars(d.datepicker._get(a,"dateFormat")),c=String.fromCharCode(b.charCode===void 0?b.keyCode:b.charCode);return b.ctrlKey||c<" "||!a||a.indexOf(c)>-1}return d.datepicker._base_doKeyPress(b)};d.datepicker._base_doKeyUp=d.datepicker._doKeyUp;d.datepicker._doKeyUp=function(b){var a=d.datepicker._getInst(b.target),c=d.datepicker._get(a,"timepicker");if(c&&c._defaults.timeOnly&&a.input.val()!=a.lastVal)try{d.datepicker._updateDatepicker(a)}catch(e){d.datepicker.log(e)}return d.datepicker._base_doKeyUp(b)};
d.datepicker._base_gotoToday=d.datepicker._gotoToday;d.datepicker._gotoToday=function(b){this._base_gotoToday(b);this._setTime(this._getInst(d(b)[0]),new Date)};d.datepicker._disableTimepickerDatepicker=function(b){var a=this._getInst(b),c=this._get(a,"timepicker");d(b).datepicker("getDate");if(c)c._defaults.showTimepicker=!1,c._updateDateTime(a)};d.datepicker._enableTimepickerDatepicker=function(b){var a=this._getInst(b),c=this._get(a,"timepicker");d(b).datepicker("getDate");if(c)c._defaults.showTimepicker=
!0,c._addTimePicker(a),c._updateDateTime(a)};d.datepicker._setTime=function(b,a){var c=this._get(b,"timepicker");if(c){var d=c._defaults,g=a?a.getHours():d.hour,h=a?a.getMinutes():d.minute,f=a?a.getSeconds():d.second;if(g<d.hourMin||g>d.hourMax||h<d.minuteMin||h>d.minuteMax||f<d.secondMin||f>d.secondMax)g=d.hourMin,h=d.minuteMin,f=d.secondMin;c.hour_slider?c.hour_slider.slider("value",g):c.hour=g;c.minute_slider?c.minute_slider.slider("value",h):c.minute=h;c.second_slider?c.second_slider.slider("value",
f):c.second=f;c._onTimeChange();c._updateDateTime(b)}};d.datepicker._setTimeDatepicker=function(b,a,c){var b=this._getInst(b),d=this._get(b,"timepicker");d&&(this._setDateFromField(b),a&&(typeof a=="string"?(d._parseTime(a,c),a=new Date,a.setHours(d.hour,d.minute,d.second)):a=new Date(a.getTime()),a.toString()=="Invalid Date"&&(a=void 0),this._setTime(b,a)))};d.datepicker._base_setDateDatepicker=d.datepicker._setDateDatepicker;d.datepicker._setDateDatepicker=function(b,a){var c=this._getInst(b),d=
a instanceof Date?new Date(a.getTime()):a;this._updateDatepicker(c);this._base_setDateDatepicker.apply(this,arguments);this._setTimeDatepicker(b,d,!0)};d.datepicker._base_getDateDatepicker=d.datepicker._getDateDatepicker;d.datepicker._getDateDatepicker=function(b,a){var c=this._getInst(b),e=this._get(c,"timepicker");if(e)return this._setDateFromField(c,a),(c=this._getDate(c))&&e._parseTime(d(b).val(),e.timeOnly)&&c.setHours(e.hour,e.minute,e.second),c;return this._base_getDateDatepicker(b,a)};d.timepicker=
new l;d.timepicker.version="0.9.5"})(jQuery);

//dateformat
var dateFormat=function(){var j=/d{1,4}|m{1,4}|yy(?:yy)?|([HhMsTt])\1?|[LloSZ]|"[^"]*"|'[^']*'/g,k=/\b(?:[PMCEA][SDP]T|(?:Pacific|Mountain|Central|Eastern|Atlantic) (?:Standard|Daylight|Prevailing) Time|(?:GMT|UTC)(?:[-+]\d{4})?)\b/g,r=/[^-+\dA-Z]/g,d=function(a,c){a=String(a);for(c=c||2;a.length<c;)a="0"+a;return a};return function(a,c,h){var f=dateFormat;arguments.length==1&&Object.prototype.toString.call(a)=="[object String]"&&!/\d/.test(a)&&(c=a,a=void 0);a=a?new Date(a):new Date;if(isNaN(a))throw SyntaxError("invalid date");
c=String(f.masks[c]||c||f.masks["default"]);c.slice(0,4)=="UTC:"&&(c=c.slice(4),h=!0);var b=h?"getUTC":"get",g=a[b+"Date"](),m=a[b+"Day"](),i=a[b+"Month"](),n=a[b+"FullYear"](),e=a[b+"Hours"](),o=a[b+"Minutes"](),p=a[b+"Seconds"](),b=a[b+"Milliseconds"](),l=h?0:a.getTimezoneOffset(),q={d:g,dd:d(g),ddd:f.i18n.dayNames[m],dddd:f.i18n.dayNames[m+7],m:i+1,mm:d(i+1),mmm:f.i18n.monthNames[i],mmmm:f.i18n.monthNames[i+12],yy:String(n).slice(2),yyyy:n,h:e%12||12,hh:d(e%12||12),H:e,HH:d(e),M:o,MM:d(o),s:p,
ss:d(p),l:d(b,3),L:d(b>99?Math.round(b/10):b),t:e<12?"a":"p",tt:e<12?"am":"pm",T:e<12?"A":"P",TT:e<12?"AM":"PM",Z:h?"UTC":(String(a).match(k)||[""]).pop().replace(r,""),o:(l>0?"-":"+")+d(Math.floor(Math.abs(l)/60)*100+Math.abs(l)%60,4),S:["th","st","nd","rd"][g%10>3?0:(g%100-g%10!=10)*g%10]};return c.replace(j,function(a){return a in q?q[a]:a.slice(1,a.length-1)})}}();
dateFormat.masks={"default":"ddd mmm dd yyyy HH:MM:ss",shortDate:"m/d/yy",mediumDate:"mmm d, yyyy",longDate:"mmmm d, yyyy",fullDate:"dddd, mmmm d, yyyy",shortTime:"h:MM TT",mediumTime:"h:MM:ss TT",longTime:"h:MM:ss TT Z",isoDate:"yyyy-mm-dd",isoTime:"HH:MM:ss",isoDateTime:"yyyy-mm-dd'T'HH:MM:ss",isoUtcDateTime:"UTC:yyyy-mm-dd'T'HH:MM:ss'Z'"};
dateFormat.i18n={dayNames:["Sun","Mon","Tue","Wed","Thu","Fri","Sat","Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],monthNames:["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec","January","February","March","April","May","June","July","August","September","October","November","December"]};Date.prototype.format=function(j,k){return dateFormat(this,j,k)};